name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
# name: main
# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches:
#       - main

# jobs:
#   lint:
#     name: Linting
#     runs-on: self-hosted
#     if: github.event_name == 'pull_request'
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v2
#       - name: Use node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 12
#       - name: Install dependencies
#         run: npm install eslint
#       - name: Run linting
#         run: npm run lint
#   unit-tests:
#     name: Unit tests
#     runs-on: self-hosted
#     if: github.event_name == 'pull_request'
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v2
#       - name: Use node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 12
#       - name: Install dependencies
#         run: npm install
#       - name: Run tests
#         run: npm test
#   deploy:
#     name: Deploy code locally
#     runs-on: self-hosted
#     if: github.event_name == 'push'
#     steps:
#       - name: Install SSH Key
#         env:
#         NODE_ENV: production
#         PORT: 8080
#         HOST: http://raspberry.pi
