name: Main
on: [push]
jobs:
  lint:
    name: Linting
    runs-on: self-hosted
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install eslint
      - name: Run linting
        run: npm run lint
  test:
    name: Testing
    runs-on: self-hosted
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
# name: main
# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches:
#       - main

#   unit-tests:
#     name: Unit tests
#     runs-on: self-hosted
#     if: github.event_name == 'pull_request'
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v2
#       - name: Use node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 12
#       - name: Install dependencies
#         run: npm install
#       - name: Run tests
#         run: npm test
#   deploy:
#     name: Deploy code locally
#     runs-on: self-hosted
#     if: github.event_name == 'push'
#     steps:
#       - name: Install SSH Key
#         env:
#         NODE_ENV: production
#         PORT: 8080
#         HOST: http://raspberry.pi
