name: Main
on:
    pull_request:
        branches:
            - main
jobs:
    test:
        name: Testing
        runs-on: self-hosted
        if: github.event_name == 'pull_request'
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Use node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 12
            - name: Install dependencies
              run: npm ci --development
            - name: Run tests
              run: npm run test
    deploy:
        needs: test
        name: Deploying
        runs-on: raspberry
        if: github.event_name == 'pull_request'
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Use node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 12
            - name: Move files
              run: cp -r * /home/joel/piserver/ && cd /home/joel/piserver
            - name: Install dependencies
              run: npm ci
            - name: Restarting pm2 service
              run: pm2 stop 0 && pm2 start 0
              env:
                  NODE_ENV: production
